version: 2.1

parameters:
  falsy-param:
    type: boolean
    default: false

jobs:
  my-job:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run: echo "Hello World!"
      - when:
          condition:
            and: 
              - not: << pipeline.parameters.falsy-param >>
            # Add condition to execute this step when the github branch is equal to 'main'
          steps:
            - run: echo "Running AND NOT false"
      - when:
          condition:
            not: << pipeline.parameters.falsy-param >>
          steps:
            - run: echo "Running not false"

workflows:
  my-workflow:
    jobs:
      - my-job
