version: 2.1

parameters:
  example:
    default: "eu-west-1"
    type: string

executors:
  ubuntu-executor:
    machine:
      image: ubuntu-2204:2023.07.2

jobs:
  my-job:
    executor: 
        name: ubuntu-executor
    steps:
      - checkout
      - run: |
          git --version
          bash ~/project/.circleci/scripts/bash.sh
          AWS_REGION=<< pipeline.parameter.example >>

workflows:
  my-workflow:
    jobs:
      - my-job
