version: 2.1

orbs:
  win: circleci/windows@5.0.0

jobs:
  my-job:
    executor: 
        name: windows/default
    steps:
      - checkout
      - run: git --version
      - run: choco install git
      - run: git --version

workflows:
  my-workflow:
    jobs:
      - my-job
