version: 2.1

jobs:
  my-job:
    docker:
      - image: node:16.14.2
    steps:
      - checkout
      - run: npm install
      - run: cat package.json
      - run: pwd && ls
      - run: |
          set -e
          npm run test --maxsockets 1

workflows:
  my-workflow:
    jobs:
      - my-job
