version: 2.1

jobs:
  my-job:
    executor: 
        name: win/default
    steps:
      - checkout
      - run: git --version
      - run: choco install git
      - run: git --version

workflows:
  my-workflow:
    jobs:
      - my-job
