version: 2.1

executors:
  ubuntu-executor:
    machine:
      image: ubuntu-2204:2023.07.2

jobs:
  my-job:
    executor: 
        name: ubuntu-executor
    steps:
      - checkout
      - run: git --version
      - run: bash echo "this is working!"

workflows:
  my-workflow:
    jobs:
      - my-job
