version: 2.1

parameters:
  example:
    description: AWS REGION
    default: "eu-west-1"
    type: string

executors:
  ubuntu-executor:
    machine:
      image: ubuntu-2204:2023.07.2

jobs:
  my-job:
    executor: 
        name: ubuntu-executor
    environment:
      AWS_REGION: << pipeline.parameters.example >>
    steps:
      - checkout
      - run: |
          git --version
          bash ~/project/.circleci/scripts/bash.sh
      - run: echo $AWS_REGION

workflows:
  my-workflow:
    jobs:
      - my-job
