version: 2.1

parameters:
  falsy-param:
    type: boolean
    default: false

jobs:
  my-job:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run: echo "Hello World!"

workflows:
  my-workflow:
    jobs:
      - my-job
