version: 2.1

jobs:
  my-job:
    docker:
      - image: cimg/node:20.5.1
    steps:
      - checkout
      - run: npm install jest
      - run: cat package.json
      - run: pwd && ls

workflows:
  my-workflow:
    jobs:
      - my-job
